### ISSUE TITLE
Build failing, broken link

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d-docs#34] opened 2019-11-10 18:50 UTC
Hey, the build instructions result in the following error for me:

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://archive.panda3d.org/branches/release/1.10.x/sphinx/

**Comment by rdb** [comment] 2019-11-10 18:52
What version of Python and pip are you using?

**Comment by BMaxV** [comment] 2019-11-10 18:56
python3.7 and pip18.1

**Comment by rdb** [comment] 2019-11-17 07:43
I'm unable to reproduce this with Python 3.7 and pip 18.1 on Linux, more info is needed.

**Comment by rdb** [comment] 2019-11-17 07:49
This looks to be a bug in a custom Debian/Ubuntu patch that they apply to pip.  I am closing this because the requirements.txt is just a suggestion for how to install the dependencies, and the actual bug is in Debian/Ubuntu.

**Closed as completed by rdb** 2019-11-17 07:49 UTC

**Comment by owford** [comment] 2019-11-17 17:30
Just to add information, I had the same problem today, on Ubuntu.
It happens with pip from apt-get : pip 9.0.1, python 3.6
It also happens when using `python3 -m venv .venv && . .venv3/bin/activate`

There are 2 ways I got it working :
- By removing the --extra-index-url from the requirements.txt
- By using pip from : `virtualenv -p python3 .venv3 && . .venv3/bin/activate`
